---
title: "4GS"
author: "Global Sustainability 4.0"
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    smooth_scroll: true
---

# View

4GlobalSustainability aims to be an open Network of Institutions (formal and non-formal), Companies and Professionals with different interests (environmental, social, economic, environmental, technological, strategic) around sustainability and issues of digital transformation and industry 4.0 on a scale Global.

# Mission

4GlobalSustainability establishes a Network of Institutions (formal and non-formal), Companies and Professionals with different interests (environmental, social, economic, environmental, technological, strategic) around sustainability and issues of digital transformation and industry 4.0.

4GlobalSustainability is an open space for research, technology transfer, entrepreneurial opportunities, team building, education, and reflection around experiences at any geographical scale or organizational level or on any dimension or topic related to global, regional and local sustainability.




